import type { SeoFaq } from "../lib/seoStructuredData";

export const SHOPIFY_STORE_LAUNCH_CHECKLIST_FAQS: readonly SeoFaq[] = [
  { question: "What do I need before launching a Shopify store in India?", answer: "At minimum, prepare a usable product catalogue, product photos, prices, shipping and return decisions, payment setup, key policy pages, a contact route, and a real test order. A polished theme cannot replace missing product information or unclear operations." },
  { question: "How long does Shopify setup take for a small product brand?", answer: "A focused launch can move quickly once product photos, names, prices, variants, policies, and payment or shipping decisions are ready. The real timeline is usually shaped by content readiness rather than theme installation alone." },
  { question: "Do I need product photos before Shopify setup starts?", answer: "Strong product photos are highly recommended before launch. Customers use photos to inspect the product, compare options, and decide whether to buy. Missing images often delay product-page work and weaken the store." },
  { question: "Does Shopify include hosting and a domain?", answer: "Shopify includes the hosted commerce platform, but a custom domain is a separate purchase or connection. Confirm current plan and domain details directly with Shopify before buying." },
  { question: "Which payment gateway can I use with Shopify in India?", answer: "India-based merchants commonly use a third-party payment provider. Confirm gateway eligibility, settlement process, payment methods, charges, and Shopify compatibility directly with the provider before launch." },
  { question: "Can Shopify handle COD in India?", answer: "Shopify supports manual payment methods, including cash on delivery. Your actual COD workflow still needs clear shipping rules, courier coordination, delivery expectations, and a process for returns or failed deliveries." },
  { question: "Do I need return, privacy, and terms pages before launch?", answer: "A product store should make its actual return or refund approach, shipping expectations, privacy information, terms, and contact route easy to find before customers reach checkout." },
  { question: "Can I connect WhatsApp to my Shopify store?", answer: "Yes. WhatsApp can be a useful support and order-update route. It works best alongside a structured product catalogue and checkout rather than as the only way a buyer can understand or place an order." },
  { question: "Do Instagram sellers need a website?", answer: "Instagram can create discovery, but a website gives customers a stable catalogue, product details, policies, and checkout path. It also makes WhatsApp conversations more specific because shoppers can inspect the product first." },
  { question: "How do I test a Shopify store before going live?", answer: "Check navigation, collection links, product variants, mobile layouts, policy links, shipping rates, payment options, confirmation emails, contact buttons, and a real test order before removing any storefront password." },
];
