import { useEffect, type ReactNode } from "react";
import { ArrowRight, Check, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";
import Footer from "../components/Footer";
import SEO from "../components/SEO";
import { useLeadFormModal } from "../components/LeadFormModalContext";
import { trackCTAClick } from "../lib/metaPixel";
import SeoArticleTracker from "../components/SeoArticleTracker";
import { getSeoRoute } from "../lib/seoRoutes";
import { buildSeoStructuredData } from "../lib/seoStructuredData";
import { SHOPIFY_STORE_LAUNCH_CHECKLIST_FAQS } from "./shopifyStoreLaunchChecklistData";

const SEO_ROUTE = getSeoRoute("/shopify-store-launch-checklist-india");
const CTA_SOURCE = SEO_ROUTE.ctaSource!;
const PRIMARY_CTA = "Plan My Shopify Store";

const SHOPIFY_CHECKLIST_URL =
  "https://help.shopify.com/en/manual/intro-to-shopify/initial-setup/setup-checklist";
const SHOPIFY_COLLECTIONS_URL = "https://help.shopify.com/en/manual/products/collections";
const SHOPIFY_MANUAL_PAYMENTS_URL =
  "https://help.shopify.com/en/manual/payments/manual-payments";
const SHOPIFY_SHIPPING_URL =
  "https://help.shopify.com/en/manual/shipping/setting-up-and-managing-your-shipping";
const SHOPIFY_POLICIES_URL = "https://help.shopify.com/en/manual/checkout-settings/refund-privacy-tos";
const SHOPIFY_TEST_ORDER_URL = "https://help.shopify.com/en/manual/checkout-settings/test-orders";
const SHOPIFY_SEO_URL = "https://help.shopify.com/en/manual/promoting-marketing/seo";
const GOOGLE_MOBILE_URL =
  "https://developers.google.com/search/docs/crawling-indexing/mobile/mobile-sites-mobile-first-indexing";
const GOOGLE_PRODUCT_URL =
  "https://developers.google.com/search/docs/appearance/structured-data/product-snippet";


const CHECKLIST = [
  ["Catalogue", "Products, variants, stock status, pricing, and collection logic are ready."],
  ["Product pages", "Images, descriptions, key details, delivery context, and size help where relevant."],
  ["Operations", "Payment gateway, COD decision, shipping zones/rates, and customer support flow."],
  ["Trust", "Refund or return, shipping, privacy, terms, and contact information are visible."],
  ["Launch QA", "Mobile review, test order, confirmation emails, links, domain, and analytics checked."],
] as const;

function ExternalTextLink({ href, children }: { href: string; children: ReactNode }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className="font-bold text-[#087746] underline decoration-black/20 underline-offset-4">{children}<ExternalLink className="ml-1 inline h-3.5 w-3.5" aria-hidden="true" /></a>;
}

function TrackedCTA({ section, label = PRIMARY_CTA, light = false, className = "" }: { section: string; label?: string; light?: boolean; className?: string }) {
  const { openLeadFormModal } = useLeadFormModal();
  return <button type="button" onClick={() => { const params = { cta_label: label, section, source_section: section, cta_source: CTA_SOURCE, destination: "lead_form_modal" }; trackCTAClick(params); openLeadFormModal(params); }} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-6 py-4 text-center text-[10px] font-black uppercase tracking-[0.14em] transition sm:text-[11px] ${light ? "border border-black/15 bg-white text-black hover:border-black/40" : "bg-[#087746] text-white hover:bg-[#065f39]"} ${className}`}>{label}<ArrowRight className="h-4 w-4 shrink-0" aria-hidden="true" /></button>;
}

function StructuredData() {
  useEffect(() => {
    if (document.getElementById(SEO_ROUTE.schemaId)) return;
    const script = document.createElement("script");
    script.id = SEO_ROUTE.schemaId;
    script.type = "application/ld+json";
    script.text = JSON.stringify(buildSeoStructuredData(SEO_ROUTE, SHOPIFY_STORE_LAUNCH_CHECKLIST_FAQS));
    document.head.appendChild(script);
    return () => script.remove();
  }, []);
  return null;
}

function HeroVisual() {
  return <svg viewBox="0 0 1200 630" className="h-full w-full" role="img" aria-label="Shopify launch checklist with product, payment, shipping and mobile store tasks"><rect width="1200" height="630" fill="#1d3329"/><circle cx="1110" cy="76" r="216" fill="#d4ebd8" opacity=".18"/><circle cx="115" cy="570" r="225" fill="#e6b56d" opacity=".13"/><rect x="70" y="82" width="425" height="465" rx="24" fill="#fffdf9"/><text x="110" y="145" fill="#087746" fontFamily="Arial, sans-serif" fontSize="17" fontWeight="700" letterSpacing="3">LAUNCH READINESS</text><text x="110" y="202" fill="#171717" fontFamily="Georgia, serif" fontSize="43" fontWeight="700">Before you go live</text>{["Products ready", "Payments tested", "Shipping clear", "Mobile checked"].map((item, index) => <g key={item}><rect x="110" y={242 + index * 58} width="32" height="32" rx="8" fill="#087746"/><path d={`M118 ${258 + index * 58}l7 7 11-14`} fill="none" stroke="#fff" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/><text x="162" y={265 + index * 58} fill="#333" fontFamily="Arial, sans-serif" fontSize="20" fontWeight="700">{item}</text></g>)}<rect x="622" y="75" width="340" height="500" rx="36" fill="#0c1511"/><rect x="638" y="95" width="308" height="460" rx="25" fill="#fffdf9"/><rect x="673" y="132" width="238" height="138" rx="15" fill="#d3d6cc"/><path d="M744 253c10-75 35-111 70-111s60 36 70 111" fill="#b58b64"/><rect x="673" y="294" width="150" height="14" rx="7" fill="#171717"/><rect x="673" y="322" width="109" height="10" rx="5" fill="#171717" opacity=".3"/><rect x="673" y="365" width="238" height="54" rx="27" fill="#087746"/><text x="728" y="399" fill="#fff" fontFamily="Arial, sans-serif" fontSize="16" fontWeight="700">CHECKOUT READY</text><rect x="993" y="185" width="142" height="150" rx="20" fill="#e6b56d"/><text x="1022" y="229" fill="#171717" fontFamily="Arial, sans-serif" fontSize="15" fontWeight="700">PAYMENT</text><path d="M1024 260h79M1024 282h48" stroke="#171717" strokeWidth="8" strokeLinecap="round" opacity=".7"/><rect x="993" y="360" width="142" height="122" rx="20" fill="#d4ebd8"/><text x="1022" y="404" fill="#171717" fontFamily="Arial, sans-serif" fontSize="15" fontWeight="700">SHIPPING</text><path d="M1024 430h79M1024 452h57" stroke="#171717" strokeWidth="8" strokeLinecap="round" opacity=".7"/></svg>;
}

function CatalogueVisual() {
  return <svg viewBox="0 0 920 360" className="h-auto w-full" role="img" aria-label="Product catalogue preparation board showing photos, variants, pricing and collection labels"><rect width="920" height="360" fill="#f4efe6"/><text x="54" y="62" fill="#171717" fontFamily="Georgia, serif" fontSize="27" fontWeight="700">A catalogue is more than a list of products</text>{[["Photos", "Front, detail, scale"], ["Variants", "Size, colour, material"], ["Price", "Clear and current"], ["Collections", "How people browse"]].map(([title, copy], index) => { const x = 54 + index * 215; return <g key={title}><rect x={x} y="105" width="180" height="188" rx="14" fill="#fffdf9" stroke="#171717" strokeWidth="1.5"/><rect x={x + 20} y="126" width="140" height="75" rx="10" fill={index % 2 ? "#d4ebd8" : "#e6b56d"}/><rect x={x + 20} y="219" width="103" height="12" rx="6" fill="#171717"/><rect x={x + 20} y="244" width="126" height="9" rx="4.5" fill="#171717" opacity=".28"/><text x={x + 20} y="275" fill="#087746" fontFamily="Arial, sans-serif" fontSize="13" fontWeight="700">{title}</text><text x={x + 20} y="314" fill="#555" fontFamily="Arial, sans-serif" fontSize="12">{copy}</text></g>; })}</svg>;
}

function CheckoutVisual() {
  return <svg viewBox="0 0 920 360" className="h-auto w-full" role="img" aria-label="Checkout flow showing payment, shipping, policy and confirmation checks"><rect width="920" height="360" fill="#eef8f1"/><text x="54" y="64" fill="#171717" fontFamily="Georgia, serif" fontSize="27" fontWeight="700">The checkout has to make operational promises visible</text>{[["Payment", "Gateway + COD"], ["Shipping", "Zones + rates"], ["Policies", "Returns + privacy"], ["Test order", "Confirmation check"]].map(([title, copy], index) => { const x = 54 + index * 215; return <g key={title}>{index < 3 && <path d={`M${x + 165} 191h42`} stroke="#087746" strokeWidth="3" strokeDasharray="7 7"/>}<rect x={x} y="130" width="165" height="122" rx="16" fill="#fffdf9" stroke="#171717" strokeWidth="1.5"/><circle cx={x + 36} cy="169" r="17" fill="#087746"/><path d={`M${x + 28} 169l6 6 11-13`} fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><text x={x + 24} y="211" fill="#171717" fontFamily="Arial, sans-serif" fontSize="17" fontWeight="700">{title}</text><text x={x + 24} y="234" fill="#555" fontFamily="Arial, sans-serif" fontSize="12">{copy}</text></g>; })}</svg>;
}

function MobileVisual() {
  return <svg viewBox="0 0 920 390" className="h-auto w-full" role="img" aria-label="Mobile storefront review checklist for a Shopify launch"><rect width="920" height="390" fill="#171717"/><rect x="327" y="35" width="266" height="320" rx="34" fill="#fdfbf6"/><rect x="348" y="57" width="224" height="118" rx="14" fill="#d4ebd8"/><path d="M397 160c9-59 29-89 61-89s52 30 61 89" fill="#a57b5b"/><rect x="348" y="196" width="138" height="12" rx="6" fill="#171717"/><rect x="348" y="221" width="90" height="9" rx="4" fill="#171717" opacity=".3"/><rect x="348" y="260" width="224" height="49" rx="24" fill="#087746"/><text x="392" y="291" fill="#fff" fontFamily="Arial, sans-serif" fontSize="14" fontWeight="700">ADD TO CART</text>{[["Readable details", 72], ["Thumb-friendly CTA", 156], ["No clipped images", 240], ["Fast path to help", 714]].map(([label, x]) => <g key={String(label)}><rect x={Number(x)} y="120" width="174" height="55" rx="12" fill="#2c4036"/><text x={Number(x) + 18} y="153" fill="#d4ebd8" fontFamily="Arial, sans-serif" fontSize="13" fontWeight="700">{label}</text></g>)}</svg>;
}

function ContextualCTA({ heading, copy, section, label = PRIMARY_CTA }: { heading: string; copy: string; section: string; label?: string }) {
  return <aside className="my-10 border-y border-black/12 bg-[#eef8f1] px-5 py-7 sm:px-7"><p className="editorial-kicker">A practical next step</p><h3 className="mt-3 font-serif text-3xl font-extrabold tracking-tight text-[#111]">{heading}</h3><p className="mb-0 mt-3 max-w-2xl text-[16px] leading-7 text-black/65">{copy}</p><TrackedCTA section={section} label={label} className="mt-6 w-full sm:w-auto" /></aside>;
}

export default function ShopifyStoreLaunchChecklistIndia() {
  return <>
    <SEO title={SEO_ROUTE.title} description={SEO_ROUTE.description} canonicalPath={SEO_ROUTE.path} type="article" image={SEO_ROUTE.ogImage} ogTitle={SEO_ROUTE.ogTitle} ogDescription={SEO_ROUTE.ogDescription} />
    <StructuredData />
    <SeoArticleTracker articleSlug={SEO_ROUTE.path} articleTitle={SEO_ROUTE.h1} articleCategory={SEO_ROUTE.category} section="launch_readiness" />
    <article className="editorial-shell">
      <header className="mx-auto max-w-6xl px-5 pb-12 pt-36 sm:px-6 md:pb-16 md:pt-44">
        <p className="editorial-kicker">Shopify launch guide · India</p>
        <h1 className="editorial-headline mt-5 max-w-5xl">Shopify Store Launch Checklist for Indian Product Brands</h1>
        <p className="editorial-deck mt-7">Before your Shopify store goes live, get the parts that make a product brand shoppable: a usable catalogue, clear payments and shipping, visible policies, mobile checkout, and one real test order.</p>
        <div className="mt-7 flex flex-wrap items-center gap-x-5 gap-y-2 border-y border-black/10 py-4 text-xs font-semibold text-black/48"><span>By {SEO_ROUTE.author}</span><span>Updated June 23, 2026</span><span>{SEO_ROUTE.readingTime}</span><span>For Indian Instagram-first product brands</span></div>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row"><TrackedCTA section="hero" label="Need help launching your Shopify store?" /><Link to="/pricing" className="inline-flex min-h-12 items-center justify-center gap-2 border border-black/15 px-6 py-4 text-center text-[10px] font-black uppercase tracking-[0.14em] text-black transition hover:border-black/40">View Readyflow Pricing <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div>
      </header>

      <figure className="mx-auto max-w-6xl px-5 sm:px-6"><div className="overflow-hidden border border-black/10 bg-[#1d3329]"><HeroVisual /></div><figcaption className="editorial-caption">A launch is not one task. It is the point where product content, customer promises, and store operations need to work together.</figcaption></figure>

      <div className="mx-auto grid max-w-6xl gap-12 px-5 py-14 sm:px-6 lg:grid-cols-[190px_minmax(0,760px)] lg:justify-center">
        <aside className="hidden lg:block"><nav className="sticky top-32 border-t-2 border-black pt-4 text-xs" aria-label="Table of contents"><p className="font-black uppercase tracking-[0.18em]">In this guide</p><div className="mt-4 space-y-3 font-semibold leading-5 text-black/48"><a href="#quick-answer" className="block hover:text-[#087746]">Quick answer</a><a href="#catalogue" className="block hover:text-[#087746]">Catalogue and pages</a><a href="#operations" className="block hover:text-[#087746]">Payments and shipping</a><a href="#mobile" className="block hover:text-[#087746]">Mobile and SEO</a><a href="#testing" className="block hover:text-[#087746]">Launch testing</a><a href="#faq" className="block hover:text-[#087746]">FAQs</a></div></nav></aside>

        <div className="editorial-copy">
          <section id="quick-answer" className="scroll-mt-28">
            <p className="first-letter:float-left first-letter:mr-2 first-letter:font-serif first-letter:text-6xl first-letter:font-bold first-letter:leading-[0.82]">A Shopify store can technically be live in an afternoon. That does not mean it is ready for an actual customer. The difference becomes obvious the first time someone arrives from an Instagram reel, cannot tell which size to choose, wonders about delivery, or reaches checkout without seeing the right payment or shipping option.</p>
            <p>This checklist is for clothing labels, jewellery sellers, boutique owners, perfume and accessory brands, handmade-product businesses, and anyone moving from DMs or WhatsApp orders to a more dependable product catalogue. It is deliberately practical: finish the things that help a buyer understand, trust, and complete an order.</p>
            <blockquote className="editorial-pullquote">“Store live” is a technical state. “Store ready” means a buyer can browse, understand the product, see the rules, pay, and know what happens next.</blockquote>
            <p>For the broader build process, see <Link to="/shopify-store-setup-india" className="font-bold text-[#087746] underline underline-offset-4">Readyflow’s Shopify store setup service</Link>. If you are still deciding whether a store is the right investment, the <Link to="/ecommerce-website-development-india" className="font-bold text-[#087746] underline underline-offset-4">ecommerce website development in India</Link> guide gives useful context.</p>
          </section>

          <section className="scroll-mt-28"><h2>What you actually need before launching a Shopify store in India</h2><div className="my-8 overflow-x-auto border border-black/12"><table className="min-w-[650px] w-full border-collapse text-left text-sm"><thead className="bg-[#171717] text-white"><tr><th className="p-4 font-bold">Area</th><th className="p-4 font-bold">Ready before launch</th></tr></thead><tbody>{CHECKLIST.map(([area, detail]) => <tr key={area} className="border-t border-black/10"><th scope="row" className="p-4 align-top font-bold">{area}</th><td className="p-4 align-top leading-6 text-black/65">{detail}</td></tr>)}</tbody></table></div><p>Shopify’s own setup guidance covers the same broad sequence: products, payments, shipping, policies, sales channels, analytics, and launch checks. Use its <ExternalTextLink href={SHOPIFY_CHECKLIST_URL}>official launch checklist</ExternalTextLink> for current platform steps, then use this guide to make the workflow fit a smaller Indian product brand.</p></section>

          <section id="catalogue" className="scroll-mt-28"><h2>1. Get the catalogue ready before the design gets fancy</h2><p>A customer cannot buy a mood board. They need product names that make sense, current prices, available variants, stock status, and a useful way to browse. Decide early whether people will shop by category, occasion, fabric, collection, price, or a small number of hero products.</p><ul className="checklist-list"><li>Prepare product names, prices, variants, stock status, weights where needed, and a clear product category.</li><li>Use product photos that show the product from the angles customers actually need.</li><li>Write the details buyers ask in DMs: material, fit, size, quantity, care, dispatch timing, and what is included.</li><li>Group products into clear collections instead of leaving a buyer in one long product feed.</li></ul><p>Shopify collections are the browsing layer that turns a catalogue into a store. Shopify explains the current options in its <ExternalTextLink href={SHOPIFY_COLLECTIONS_URL}>collections documentation</ExternalTextLink>.</p><figure className="my-9 overflow-hidden border border-black/10"><CatalogueVisual /></figure><h3>Product page essentials</h3><p>At a minimum, each product page should make the product, price, variant, delivery context, and next step easy to scan. Clothing needs a real size chart or fit guidance. Jewellery benefits from material, dimensions, care, and close-up images. A store for Instagram sellers should answer the questions that normally create a long DM thread.</p><p>For more category-specific detail, use the <Link to="/clothing-brand-website" className="font-bold text-[#087746] underline underline-offset-4">clothing brand website guide</Link> or the <Link to="/jewellery-ecommerce-website" className="font-bold text-[#087746] underline underline-offset-4">jewellery ecommerce website guide</Link>.</p></section>

          <ContextualCTA heading="Products and photos ready, but the store structure is still unclear?" copy="Readyflow’s focused Shopify launch starts at ₹14,999 and covers the practical foundation: theme, homepage, collections, product-page structure, policy pages, mobile review, and setup guidance." section="catalogue_cta" label="See Readyflow’s ₹14,999 Shopify launch setup" />

          <section><h2>2. Build a homepage that helps people shop</h2><p>The homepage does not need every idea your brand has ever had. It needs a confident first impression, a clear route to featured collections or products, proof that the store is legitimate, and an easy way to get help. A clean navigation, visible search where useful, contact details, and policy links do more work than decorative sections alone.</p><p>For Instagram-first brands, use the store as the stable destination behind the bio link. Instagram creates the visit; the website should make browsing, checkout, and a useful WhatsApp question possible. Read more about a <Link to="/instagram-brand-shopify-store" className="font-bold text-[#087746] underline underline-offset-4">Shopify store for Instagram brands</Link>.</p></section>

          <section id="operations" className="scroll-mt-28"><h2>3. Decide payment, COD, shipping, and policies before launch</h2><p>These are operational decisions, not finishing touches. India-based Shopify sellers commonly need to choose a third-party payment provider, decide whether COD makes sense for their business, set realistic shipping zones and rates, and explain what happens if an order must be returned or exchanged.</p><h3>Payments and COD</h3><p>Do not assume a gateway is ready just because its application has been started. Confirm merchant eligibility, supported payment methods, settlement details, charges, and the actual checkout experience. Shopify documents <ExternalTextLink href={SHOPIFY_MANUAL_PAYMENTS_URL}>manual payment methods</ExternalTextLink>, including cash on delivery. Whether you offer COD is a business decision: make its rules and delivery promise clear.</p><h3>Shipping and customer promises</h3><p>Set up the places you serve, rates or thresholds, dispatch expectations, and product-specific exceptions before advertising nationwide delivery. Shopify’s <ExternalTextLink href={SHOPIFY_SHIPPING_URL}>shipping setup guidance</ExternalTextLink> is useful for the platform mechanics. Your published shipping language must reflect what your brand can actually fulfil.</p><h3>Policy and contact pages</h3><p>Make the actual return or refund policy, shipping policy, privacy policy, terms, and contact route easy to find. Shopify lets merchants create and surface policy pages; see its <ExternalTextLink href={SHOPIFY_POLICIES_URL}>policy guidance</ExternalTextLink>. This is general operational guidance, not legal advice: make policies reflect your own process.</p><figure className="my-9 overflow-hidden border border-black/10"><CheckoutVisual /></figure></section>

          <section id="mobile" className="scroll-mt-28"><h2>4. Treat mobile layout, SEO, and analytics as launch requirements</h2><p>Most Instagram and WhatsApp-led traffic arrives on a phone. Check that collection tiles, product images, variant controls, cart buttons, forms, policy links, and support actions fit comfortably on a small screen. Google uses the mobile version of a site for indexing, which is why mobile usability belongs in the launch checklist rather than a later wishlist.</p><figure className="my-9 overflow-hidden border border-black/10"><MobileVisual /></figure><p>Before launch, set useful page titles, descriptions, image alt text, and collection copy. Shopify provides useful SEO foundations, while its <ExternalTextLink href={SHOPIFY_SEO_URL}>SEO documentation</ExternalTextLink> explains the platform controls. Google’s <ExternalTextLink href={GOOGLE_MOBILE_URL}>mobile-first indexing guidance</ExternalTextLink> and <ExternalTextLink href={GOOGLE_PRODUCT_URL}>product structured-data guidance</ExternalTextLink> are sensible references when you are ready to deepen technical search work.</p><p>Also verify your analytics basics: a page visit should register, CTA clicks should be measurable, and no personal form details should be pushed into analytics events. You do not need a complex measurement program before launch, but you do need enough signal to know whether visitors reach product pages, start a form, or abandon checkout.</p></section>

          <section id="testing" className="scroll-mt-28"><h2>5. Run a real launch test, not just a visual review</h2><p>Clicking around your own homepage is not enough. Use a phone, behave like a new customer, and complete the whole path. Shopify’s <ExternalTextLink href={SHOPIFY_TEST_ORDER_URL}>test-order guidance</ExternalTextLink> covers the platform side; your job is to test the customer experience and the operations behind it.</p><div className="my-8 grid gap-3 sm:grid-cols-2">{["Navigation and collection links open correctly.", "Product variants, size help, and prices are accurate.", "Cart and checkout work on a phone.", "Payment and COD choices match the actual plan.", "Shipping rates and delivery language are clear.", "Policy and contact links are visible and correct.", "Order and customer emails arrive as expected.", "Domain, SSL, and storefront access are ready for go-live."].map((item) => <div key={item} className="flex gap-3 border border-black/12 bg-[#f3f0e9] p-4 text-sm font-semibold leading-6 text-black/70"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#087746]" />{item}</div>)}</div><h3>Common launch mistakes</h3><ul><li>Launching with incomplete photos, uncertain prices, or placeholder product copy.</li><li>Making the homepage beautiful but leaving collections and product pages difficult to use.</li><li>Offering COD or shipping promises without an operating process behind them.</li><li>Hiding policy pages or making the contact route hard to find.</li><li>Skipping a mobile checkout test and discovering errors only after paid traffic arrives.</li></ul></section>

          <section><h2>What can improve after launch—and what cannot wait</h2><p>You can refine editorial content, add reviews, improve collection storytelling, run experiments, and expand automation after launch. Do not defer the things that block a basic order: product information, price, payment choice, shipping setup, policy visibility, mobile usability, and a test order.</p><p>If you are comparing platform approaches before committing, read <Link to="/shopify-vs-woocommerce-india" className="font-bold text-[#087746] underline underline-offset-4">Shopify vs WooCommerce for Indian sellers</Link>. If the question is budget and scope, the useful next read is <Link to="/shopify-store-setup-cost-india" className="font-bold text-[#087746] underline underline-offset-4">Shopify store setup cost in India</Link>.</p></section>

          <ContextualCTA heading="Need a clean launch without turning the checklist into a second job?" copy="Readyflow builds focused, mobile-first Shopify stores for Indian product brands. The ₹14,999 setup covers the core launch work; Shopify, domain, apps, photography, and advertising remain separate business costs." section="final_article_cta" />

          <aside className="my-12 border-y border-black/12 bg-[#f3f0e9] px-6 py-7"><p className="editorial-kicker">Related Readyflow reading</p><h2 className="mt-3 font-serif text-2xl font-extrabold tracking-tight">Continue the launch plan</h2><ul className="mt-5 space-y-3 text-[15px] font-semibold"><li><Link to="/" className="text-[#087746] underline underline-offset-4">Readyflow homepage</Link></li><li><Link to="/pricing" className="text-[#087746] underline underline-offset-4">Readyflow pricing</Link></li><li><Link to="/work" className="text-[#087746] underline underline-offset-4">Readyflow work archive</Link></li><li><Link to="/shopify-store-setup-india" className="text-[#087746] underline underline-offset-4">Shopify store setup in India</Link></li></ul></aside>

          <section id="faq" className="scroll-mt-28"><p className="editorial-kicker">Frequently asked questions</p><h2 className="!mt-4">Before you launch: practical answers</h2><div className="divide-y divide-black/12 border-y border-black/12">{SHOPIFY_STORE_LAUNCH_CHECKLIST_FAQS.map((faq, index) => <details key={faq.question} open={index === 0} className="group"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 font-bold">{faq.question}<span className="text-xl transition group-open:rotate-45">+</span></summary><p className="pb-5 !mb-0 text-[16px] leading-7 text-black/62">{faq.answer}</p></details>)}</div><TrackedCTA section="faq" label="Plan My Shopify Store" className="mt-8 w-full sm:w-auto" /></section>
        </div>
      </div>
      <section className="border-y border-black/12 bg-[#eef8f1] px-5 py-16 sm:px-6"><div className="mx-auto max-w-3xl text-center"><p className="editorial-kicker">The practical next step</p><h2 className="mt-4 font-serif text-4xl font-extrabold leading-tight tracking-tight md:text-5xl">Launch with the essentials handled, then keep improving.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-8 text-black/62">If your products and basic content are ready, Readyflow can help turn the checklist into a clean mobile-first Shopify launch.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><TrackedCTA section="final_cta" label="Plan My Shopify Store" /><Link to="/work" className="inline-flex min-h-12 items-center justify-center gap-2 border border-black/15 px-6 py-4 text-center text-[10px] font-black uppercase tracking-[0.14em] text-black transition hover:border-black/40">See Real Stores Built by Readyflow <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div></div></section>
    </article>
    <Footer />
  </>;
}
